theme: minima
title: Yes
author: VictorP
email: vrthk@etlgr.com
description: Cool new web-site direct from github and internet connections.

# social links
twitter_username: vpspsps # DO NOT include the @ character, or else the build will fail!
github_username:  vorthkor # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
